### ISSUE TITLE
Broken OF 1.18.1

### ISSUE THREAD

**Issue by Spyro24** [MMCInstances/OptifineInstances#22]
Of instanz 1.18.1 is broken

[17:47:28] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[17:47:28] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[17:47:28] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[17:47:28] [main/INFO]: [OptiFine] OptiFineTweaker: acceptOptions
[17:47:28] [main/INFO]: [OptiFine] OptiFineTweaker: injectIntoClassLoader
[17:47:28] [main/INFO]: [OptiFine] OptiFine ClassTransformer
[17:47:28] [main/INFO]: [OptiFine] OptiFine ZIP file: /home/pi/ins/1.18.1/libraries/OptiFine_1.18.1_HD_U_H4.jar
[17:47:28] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchArguments
[17:47:28] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchTarget
[17:47:29] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:47:30] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.3.jar:2.3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodError: 'long ad.b()'
	at net.minecraft.client.main.Main.main(SourceFile:71) ~[Main.class:?]
	... 14 more
Der Prozess wurde mit Status 1 beendet.

playse repair the intsanz

**Comment by Slddev** [comment]
Please check #17
